### PR TITLE
Add static checks

### PR DESCRIPTION
**Pull request by mik-laj**
Code quality is important, especially in an open-source project where the code will be maintained for a long time and by multiple people. So I would like to suggest using https://pre-commit.com framework to automate a lot of stuff and assure that our code is nice.

It plays nicely with Github action and allows a plethora of checks (building TOC, license insert, liniting etc) and gives the possibility to build custom ones. For example, here's configuration from Apache Airflow:
https://github.com/apache/airflow/blob/master/.pre-commit-config.yaml

For now I only focused on the basic checks, but in the future, we may add some more Go project-specific checks e.g.[golangci-lint](https://github.com/golangci/golangci-lint) or [other checks](https://github.com/dnephin/pre-commit-golang)

### CODE REVIEW

**Comment by mik-laj** [comment]
@tstromberg  WDYT?

**Review by TobKed — APPROVED** [review]

**Comment by TobKed** [comment]
I have suggestion that for easier review of changes which add linters is to make separate commits for adding linters and parsing project files to distinguish manual and automatic changes.

**Comment by mik-laj** [comment]
@TobKed  This is not a very big project. Do you think it's worth the extra work to keep these changes separate?

**Comment by TobKed** [comment]
@mik-laj in this case, when it is already done it is probably not worth extra work.  However in general, IMHO, it is good practice to keep manual/automatic changes separated 😄

**Comment by tstromberg** [comment]
I'm not sure how I feel about the TOC changes yet. - but at this point, let's just get this in and sort out the changes later.

**Pull request merged**
